export const chords = {
  type: {
    positions: ["root", "third", "fifth", "seventh"],
    major: [ 0, 4, 3 ],
    minor: [ 0, 4, 4 ],
    augmented: [ 0, 4, 4 ],
    diminished: [ 0, 3, 3 ],
    major7: [ 0, 4, 3, 4 ],
    minor7: [ 0, 4, 4, 3 ],
    aug7: [ 0, 4, 4, 2 ],
    "half-dim7": [ 0, 3, 3, 4 ],
    dim7: [ 0, 3, 3, 3 ],
  },
  major: [
    { name: "C-major", label: "C", notes: ["C", "E", "G"], audio: ["C", "E", "G2"], chordAudio: "C"},
    { name: "F-major", label: "F", notes: ["F", "A", "C"], audio: ["F2", "A2", "C2"], chordAudio: "F"},
    { name: "Bb-major", label: "Bb", notes: ["Bb", "D", "F"], audio: ["Bb", "D", "F2"], chordAudio: "Bb"},
    { name: "Eb-major", label: "Eb", notes: ["Eb", "G", "Bb"], audio: ["Eb", "G2", "Bb2"], chordAudio: "Eb"},
    { name: "Ab-major", label: "Ab", notes: ["Ab", "C", "Eb"], audio: ["Ab2", "C2", "Eb2"], chordAudio: "Ab"},
    { name: "Db-major", label: "Db", notes: ["Db", "F", "Ab"], audio: ["Db", "F2", "Ab2"], chordAudio: "Db"},
    { name: "Gb-major", label: "Gb", notes: ["Gb", "Bb", "Db"], audio: ["Gb2", "Bb2", "Db2"], chordAudio: "Gb"},
    { name: "C#-major", label: "C#", notes: ["C#", "E#", "G#"], audio: ["Db", "F2", "Ab2"], chordAudio: "Db"},
    { name: "F#-major", label: "F#", notes: ["F#", "A#", "C#"], audio: ["Gb2", "Bb2", "Db2"], chordAudio: "Gb"},
    { name: "B-major", label: "B", notes: ["B", "D#", "F#"], audio: ["B", "Eb", "Gb2"], chordAudio: "B"},
    { name: "E-major", label: "E", notes: ["E", "G#", "B"], audio: ["E", "Ab2", "B2"], chordAudio: "E"},
    { name: "A-major", label: "A", notes: ["A", "C#", "E"], audio: ["A2", "Db2", "E2"], chordAudio: "A"},
    { name: "D-major", label: "D", notes: ["D", "F#", "A"], audio: ["D", "Gb2", "A2"], chordAudio: "D"},
    { name: "G-major", label: "G", notes: ["G", "B", "D"], audio: ["G2", "B2", "D2"], chordAudio: "G"},
  ],
  minor: [
    { name: "C-minor", label: "Cm", notes: ["C", "Eb", "G"], audio: ["C", "Eb", "G2"], chordAudio: "Cm"},
    { name: "F-minor", label: "Fm", notes: ["F", "Ab", "C"], audio: ["F2", "Ab2", "C2"], chordAudio: "Fm"},
    { name: "Bb-minor", label: "Bbm", notes: ["Bb", "Db", "F"], audio: ["Bb", "Db", "F2"], chordAudio: "Bbm"},
    { name: "Eb-minor", label: "Ebm", notes: ["Eb", "Gb", "Bb"], audio: ["Eb", "Gb2", "Bb2"], chordAudio: "Ebm"},
    { name: "Ab-minor", label: "Abm", notes: ["Ab", "Cb", "Eb"], audio: ["Ab2", "B2", "Eb2"], chordAudio: "Abm"},
    { name: "Db-minor", label: "Dbm", notes: ["Db", "Fb", "Ab"], audio: ["Db", "E", "Ab2"], chordAudio: "Dbm"},
    { name: "Gb-minor", label: "Gbm", notes: ["Gb", "Bbb", "Db"], audio: ["Gb", "A", "Db"], chordAudio: "Gbm"},
    { name: "G#-minor", label: "G#m", notes: ["G#", "B", "D#"], audio: ["Ab2", "B2", "Eb2"], chordAudio: "Abm"},
    { name: "C#-minor", label: "C#m", notes: ["C#", "E", "G#"], audio: ["Db", "E", "Ab2"], chordAudio: "Dbm"},
    { name: "F#-minor", label: "F#m", notes: ["F#", "A", "C#"], audio: ["Gb", "A", "Db"], chordAudio: "Gbm"},
    { name: "B-minor", label: "Bm", notes: ["B", "D", "F#"], audio: ["B", "D", "Gb2"], chordAudio: "Bm"},
    { name: "E-minor", label: "Em", notes: ["E", "G", "B"], audio: ["E", "G2", "B2"], chordAudio: "Em"},
    { name: "A-minor", label: "Am", notes: ["A", "C", "E"], audio: ["A2", "C2", "E2"], chordAudio: "Am"},
    { name: "D-minor", label: "Dm", notes: ["D", "F", "A"], audio: ["D", "F2", "A2"], chordAudio: "Dm"},
    { name: "G-minor", label: "Gm", notes: ["G", "Bb", "D"], audio: ["G2", "Bb2", "D2"], chordAudio: "Gm"},
  ],
  augmented: [
    { name: "C-augmented", label: "C+", notes: ["C", "E", "G#"], audio: ["C", "E", "Ab2"], chordAudio: "Caug"},
    { name: "F-augmented", label: "F+", notes: ["F", "A", "C#"], audio: ["F2", "A2", "Db2"], chordAudio: "Faug"},
    { name: "Bb-augmented", label: "Bb+", notes: ["Bb", "D", "F#"], audio: ["Bb", "D", "Gb2"], chordAudio: "Bbaug"},
    { name: "Eb-augmented", label: "Eb+", notes: ["Eb", "G", "B"], audio: ["Eb", "G2", "B2"], chordAudio: "Ebaug"},
    { name: "Ab-augmented", label: "Ab+", notes: ["Ab", "C", "E"], audio: ["Ab2", "C2", "E2"], chordAudio: "Abaug"},
    { name: "Db-augmented", label: "Db+", notes: ["Db", "F", "A"], audio: ["Db", "F2", "A2"], chordAudio: "Dbaug"},
    { name: "Gb-augmented", label: "Gb+", notes: ["Gb", "Bb", "D"], audio: ["Gb2", "Bb2", "D2"], chordAudio: "Gbaug"},
    { name: "C#-augmented", label: "C#+", notes: ["C#", "E#", "G##"], audio: ["Db", "F2", "A2"], chordAudio: "Dbaug"},
    { name: "F#-augmented", label: "F#+", notes: ["F#", "A#", "C##"], audio: ["Gb2", "Bb2", "D2"], chordAudio: "Gbaug"},
    { name: "B-augmented", label: "B+", notes: ["B", "D#", "F##"], audio: ["B", "Eb", "G2"], chordAudio: "Baug"},
    { name: "E-augmented", label: "E+", notes: ["E", "G#", "B#"], audio: ["E", "Ab2", "C2"], chordAudio: "Eaug"},
    { name: "A-augmented", label: "A+", notes: ["A", "C#", "E#"], audio: ["A2", "Db2", "F2"], chordAudio: "Aaug"},
    { name: "D-augmented", label: "D+", notes: ["D", "F#", "A#"], audio: ["D", "Gb2", "Bb2"], chordAudio: "Daug"},
    { name: "G-augmented", label: "G+", notes: ["G", "B", "D#"], audio: ["G2", "B2", "Eb2"], chordAudio: "Gaug"},
  ],
  diminished: [
    { name: "C-diminished", label: "C°", notes: ["C", "Eb", "Gb"], audio: ["C", "Eb", "Gb2"], chordAudio: "Cdim"},
    { name: "F-diminished", label: "F°", notes: ["F", "Ab", "Cb"], audio: ["F2", "Ab2", "B2"], chordAudio: "Fdim"},
    { name: "Bb-diminished", label: "Bb°", notes: ["Bb", "Db", "Fb"], audio: ["Bb", "Db", "E"], chordAudio: "Bbdim"},
    { name: "Eb-diminished", label: "Eb°", notes: ["Eb", "Gb", "Bbb"], audio: ["Eb", "Gb2", "A2"], chordAudio: "Ebdim"},
    { name: "Ab-diminished", label: "Ab°", notes: ["Ab", "Cb", "Ebb"], audio: ["Ab2", "B2", "D2"], chordAudio: "Abdim"},
    { name: "Db-diminished", label: "Db°", notes: ["Db", "Fb", "Abb"], audio: ["Db", "E", "G2"], chordAudio: "Dbdim"},
    { name: "Gb-diminished", label: "Gb°", notes: ["Gb", "Bbb", "Dbb"], audio: ["Gb", "A", "C"], chordAudio: "Gbdim"},
    { name: "G#-diminished", label: "G#°", notes: ["G#", "B", "D"], audio: ["Ab2", "B2", "D2"], chordAudio: "Abdim"},
    { name: "C#-diminished", label: "C#°", notes: ["C#", "E", "G"], audio: ["Db", "E", "G2"], chordAudio: "Dbdim"},
    { name: "F#-diminished", label: "F#°", notes: ["F#", "A", "C"], audio: ["Gb", "A", "C"], chordAudio: "Gbdim"},
    { name: "B-diminished", label: "B°", notes: ["B", "D", "F"], audio: ["B", "D", "F2"], chordAudio: "Bdim"},
    { name: "E-diminished", label: "E°", notes: ["E", "G", "Bb"], audio: ["E", "G2", "Bb2"], chordAudio: "Edim"},
    { name: "A-diminished", label: "A°", notes: ["A", "C", "Eb"], audio: ["A2", "C2", "Eb2"], chordAudio: "Adim"},
    { name: "D-diminished", label: "D°", notes: ["D", "F", "Ab"], audio: ["D", "F2", "Ab2"], chordAudio: "Ddim"},
    { name: "G-diminished", label: "G°", notes: ["G", "Bb", "Db"], audio: ["G2", "Bb2", "Db2"], chordAudio: "Gdim"},
  ],
  major7: [
    { name: "C-major7", label: "CM7", notes: ["C", "E", "G", "B"], audio: ["C", "E", "G2", "B2"], chordAudio: "CMajor7"},
    { name: "F-major7", label: "FM7", notes: ["F", "A", "C", "E"], audio: ["F2", "A2", "C2", "E2"], chordAudio: "FMajor7"},
    { name: "Bb-major7", label: "BbM7", notes: ["Bb", "D", "F", "A"], audio: ["Bb", "D", "F2", "A2"], chordAudio: "BbMajor7"},
    { name: "Eb-major7", label: "EbM7", notes: ["Eb", "G", "Bb", "D"], audio: ["Eb", "G2", "Bb2", "D2"], chordAudio: "EbMajor7"},
    { name: "Ab-major7", label: "AbM7", notes: ["Ab", "C", "Eb", "G"], audio: ["Ab2", "C2", "Eb2", "G2"], chordAudio: "AbMajor7"},
    { name: "Db-major7", label: "DbM7", notes: ["Db", "F", "Ab", "C"], audio: ["Db", "F2", "Ab2", "C2"], chordAudio: "DbMajor7"},
    { name: "Gb-major7", label: "GbM7", notes: ["Gb", "Bb", "Db", "F"], audio: ["Gb2", "Bb2", "Db2", "F2"], chordAudio: "GbMajor7"},
    { name: "C#-major7", label: "C#M7", notes: ["C#", "E#", "G#", "B#"], audio: ["Db", "F2", "Ab2", "C2"], chordAudio: "DbMajor7"},
    { name: "F#-major7", label: "F#M7", notes: ["F#", "A#", "C#", "E#"], audio: ["Gb2", "Bb2", "Db2", "F2"], chordAudio: "GbMajor7"},
    { name: "B-major7", label: "BM7", notes: ["B", "D#", "F#", "A#"], audio: ["B", "Eb", "Gb2", "Bb2"], chordAudio: "BMajor7"},
    { name: "E-major7", label: "EM7", notes: ["E", "G#", "B", "D#"], audio: ["E", "Ab2", "B2", "Eb2"], chordAudio: "EMajor7"},
    { name: "A-major7", label: "AM7", notes: ["A", "C#", "E", "G#"], audio: ["A", "Db", "E", "Ab2"], chordAudio: "AMajor7"},
    { name: "D-major7", label: "DM7", notes: ["D", "F#", "A", "C#"], audio: ["D", "Gb2", "A2", "Db2"], chordAudio: "DMajor7"},
    { name: "G-major7", label: "GM7", notes: ["G", "B", "D", "F#"], audio: ["G", "B", "D", "Gb2"], chordAudio: "GMajor7"},
  ],
  minor7: [
    { name: "C-minor7", label: "Cm7", notes: ["C", "Eb", "G", "Bb"], audio: ["C", "Eb", "G2", "Bb2"], chordAudio: "Cminor7"},
    { name: "F-minor7", label: "Fm7", notes: ["F", "Ab", "C", "Eb"], audio: ["F2", "Ab2", "C2", "Eb2"], chordAudio: "Fminor7"},
    { name: "Bb-minor7", label: "Bbm7", notes: ["Bb", "Db", "F", "Ab"], audio: ["Bb", "Db", "F2", "Ab2"], chordAudio: "Bbminor7"},
    { name: "Eb-minor7", label: "Ebm7", notes: ["Eb", "Gb", "Bb", "Db"], audio: ["Eb", "Gb2", "Bb2", "Db2"], chordAudio: "Ebminor7"},
    { name: "Ab-minor7", label: "Abm7", notes: ["Ab", "Cb", "Eb", "Gb"], audio: ["Ab", "B", "Eb", "Gb2"], chordAudio: "Abminor7"},
    { name: "Db-minor7", label: "Dbm7", notes: ["Db", "Fb", "Ab", "Cb"], audio: ["Db", "E", "Ab2", "B2"], chordAudio: "Dbminor7"},
    { name: "Gb-minor7", label: "Gbm7", notes: ["Gb", "Bbb", "Db", "Fb"], audio: ["Gb", "A", "Db", "E"], chordAudio: "Gbminor7"},
    { name: "G#-minor7", label: "G#m7", notes: ["G#", "B", "D#", "F#"], audio: ["Ab", "B", "Eb", "Gb2"], chordAudio: "Abminor7"},
    { name: "C#-minor7", label: "C#m7", notes: ["C#", "E", "G#", "B"], audio: ["Db", "E", "Ab2", "B2"], chordAudio: "Dbminor7"},
    { name: "F#-minor7", label: "F#m7", notes: ["F#", "A", "C#", "E"], audio: ["Gb", "A", "Db", "E"], chordAudio: "Gbminor7"},
    { name: "B-minor7", label: "Bm7", notes: ["B", "D", "F#", "A"], audio: ["B", "D", "Gb2", "A2"], chordAudio: "Bminor7"},
    { name: "E-minor7", label: "Em7", notes: ["E", "G", "B", "D"], audio: ["E", "G2", "B2", "D2"], chordAudio: "Eminor7"},
    { name: "A-minor7", label: "Am7", notes: ["A", "C", "E", "G"], audio: ["A", "C", "E", "G2"], chordAudio: "Aminor7"},
    { name: "D-minor7", label: "Dm7", notes: ["D", "F", "A", "C"], audio: ["D", "F2", "A2", "C2"], chordAudio: "Dminor7"},
    { name: "G-minor7", label: "Gm7", notes: ["G", "Bb", "D", "F"], audio: ["G", "Bb", "D", "F2"], chordAudio: "Gminor7"},
  ],
  aug7: [
    { name: "C-augmented7", label: "C+7", notes: ["C", "E", "G#", "Bb"], audio: ["C", "E", "Ab2", "Bb2"], chordAudio: "Caug7"},
    { name: "F-augmented7", label: "F+7", notes: ["F", "A", "C#", "Eb"], audio: ["F2", "A2", "Db2", "Eb2"], chordAudio: "Faug7"},
    { name: "Bb-augmented7", label: "Bb+7", notes: ["Bb", "D", "F#", "Ab"], audio: ["Bb", "D", "Gb2", "Ab2"], chordAudio: "Bbaug7"},
    { name: "Eb-augmented7", label: "Eb+7", notes: ["Eb", "G", "B", "Db"], audio: ["Eb", "G2", "B2", "Db2"], chordAudio: "Ebaug7"},
    { name: "Ab-augmented7", label: "Ab+7", notes: ["Ab", "C", "E", "Gb"], audio: ["Ab", "C", "E", "Gb2"], chordAudio: "Abaug7"},
    { name: "Db-augmented7", label: "Db+7", notes: ["Db", "F", "A", "Cb"], audio: ["Db", "F2", "A2", "B2"], chordAudio: "Dbaug7"},
    { name: "Gb-augmented7", label: "Gb+7", notes: ["Gb", "Bb", "D", "Fb"], audio: ["Gb", "Bb", "D", "E"], chordAudio: "Gbaug7"},
    { name: "C#-augmented7", label: "C#+7", notes: ["C#", "E#", "G##", "B"], audio: ["Db", "F2", "A2", "B2"], chordAudio: "Dbaug7"},
    { name: "F#-augmented7", label: "F#+7", notes: ["F#", "A#", "C##", "E"], audio: ["Gb", "Bb", "D", "E"], chordAudio: "Gbaug7"},
    { name: "B-augmented7", label: "B+7", notes: ["B", "D#", "F##", "A"], audio: ["B", "Eb", "G2", "A2"], chordAudio: "Baug7"},
    { name: "E-augmented7", label: "E+7", notes: ["E", "G#", "B#", "D"], audio: ["E", "Ab2", "C2", "D2"], chordAudio: "Eaug7"},
    { name: "A-augmented7", label: "A+7", notes: ["A", "C#", "E#", "G"], audio: ["A", "Db", "F2", "G2"], chordAudio: "Aaug7"},
    { name: "D-augmented7", label: "D+7", notes: ["D", "F#", "A#", "C"], audio: ["D", "Gb2", "Bb2", "C2"], chordAudio: "Daug7"},
    { name: "G-augmented7", label: "G+7", notes: ["G", "B", "D#", "F"], audio: ["G", "B", "Eb", "F2"], chordAudio: "Gaug7"},
  ],
  "half-dim7": [
    { name: "C-half-dim7", label: "Cø7", notes: ["C", "Eb", "Gb", "Bb"], audio: ["C", "Eb", "Gb2", "Bb2"], chordAudio: "C-half-dim7"},
    { name: "F-half-dim7", label: "Fø7", notes: ["F", "Ab", "Cb", "Eb"], audio: ["F2", "Ab2", "B2", "Eb2"], chordAudio: "F-half-dim7"},
    { name: "Bb-half-dim7", label: "Bbø7", notes: ["Bb", "Db", "Fb", "Ab"], audio: ["Bb", "Db", "E", "Ab2"], chordAudio: "Bb-half-dim7"},
    { name: "Eb-half-dim7", label: "Ebø7", notes: ["Eb", "Gb", "Bbb", "Db"], audio: ["Eb", "Gb2", "A2", "Db2"], chordAudio: "Eb-half-dim7"},
    { name: "Ab-half-dim7", label: "Abø7", notes: ["Ab", "Cb", "Ebb", "Gb"], audio: ["Ab", "B", "D", "Gb2"], chordAudio: "Ab-half-dim7"},
    { name: "Db-half-dim7", label: "Dbø7", notes: ["Db", "Fb", "Abb", "Cb"], audio: ["Db", "E", "G2", "B2"], chordAudio: "Db-half-dim7"},
    { name: "Gb-half-dim7", label: "Gbø7", notes: ["Gb", "Bbb", "Dbb", "Fb"], audio: ["Gb", "A", "C", "E"], chordAudio: "Gb-half-dim7"},
    { name: "G#-half-dim7", label: "G#ø7", notes: ["G#", "B", "D", "F#"], audio: ["Ab", "B", "D", "Gb2"], chordAudio: "Ab-half-dim7"},
    { name: "C#-half-dim7", label: "C#ø7", notes: ["C#", "E", "G", "B"], audio: ["Db", "E", "G2", "B2"], chordAudio: "Db-half-dim7"},
    { name: "F#-half-dim7", label: "F#ø7", notes: ["F#", "A", "C", "E"], audio: ["Gb", "A", "C", "E"], chordAudio: "Gb-half-dim7"},
    { name: "B-half-dim7", label: "Bø7", notes: ["B", "D", "F", "A"], audio: ["B", "D", "F2", "A2"], chordAudio: "B-half-dim7"},
    { name: "E-half-dim7", label: "Eø7", notes: ["E", "G", "Bb", "D"], audio: ["E", "G2", "Bb2", "D2"], chordAudio: "E-half-dim7"},
    { name: "A-half-dim7", label: "Aø7", notes: ["A", "C", "Eb", "G"], audio: ["A", "C", "Eb", "G2"], chordAudio: "A-half-dim7"},
    { name: "D-half-dim7", label: "Dø7", notes: ["D", "F", "Ab", "C"], audio: ["D", "F2", "Ab2", "C2"], chordAudio: "D-half-dim7"},
    { name: "G-half-dim7", label: "Gø7", notes: ["G", "Bb", "Db", "F"], audio: ["G", "Bb", "Db", "F2"], chordAudio: "G-half-dim7"},
  ],
  dim7: [
    { name: "C-diminished7", label: "C°7", notes: ["C", "Eb", "Gb", "Bbb"], audio: ["C", "Eb", "Gb2", "A2"], chordAudio: "Cdim"},
    { name: "F-diminished7", label: "F°7", notes: ["F", "Ab", "Cb", "Ebb"], audio: ["F2", "Ab2", "B2", "D2"], chordAudio: "Fdim"},
    { name: "Bb-diminished7", label: "Bb°7", notes: ["Bb", "Db", "Fb", "Abb"], audio: ["Bb", "Db", "E", "G2"], chordAudio: "Bbdim"},
    { name: "Eb-diminished7", label: "Eb°7", notes: ["Eb", "Gb", "Bbb", "Dbb"], audio: ["Eb", "Gb2", "A2", "C2"], chordAudio: "Ebdim"},
    { name: "Ab-diminished7", label: "Ab°7", notes: ["Ab", "Cb", "Ebb", "Gbb"], audio: ["Ab", "B", "D", "F2"], chordAudio: "Abdim"},
    { name: "Db-diminished7", label: "Db°7", notes: ["Db", "Fb", "Abb", "Cbb"], audio: ["Db", "E", "G2", "Bb2"], chordAudio: "Dbdim"},
    { name: "Gb-diminished7", label: "Gb°7", notes: ["Gb", "Bbb", "Dbb", "Fbb"], audio: ["Gb", "A", "C", "Eb"], chordAudio: "Gbdim"},
    { name: "G#-diminished7", label: "G#°7", notes: ["G#", "B", "D", "F"], audio: ["Ab", "B", "D", "F2"], chordAudio: "Abdim"},
    { name: "C#-diminished7", label: "C#°7", notes: ["C#", "E", "G", "Bb"], audio: ["Db", "E", "G2", "Bb2"], chordAudio: "Dbdim"},
    { name: "F#-diminished7", label: "F#°7", notes: ["F#", "A", "C", "Eb"], audio: ["Gb", "A", "C", "Eb"], chordAudio: "Gbdim"},
    { name: "B-diminished7", label: "B°7", notes: ["B", "D", "F", "Ab"], audio: ["B", "D", "F2", "Ab2"], chordAudio: "Bdim"},
    { name: "E-diminished7", label: "E°7", notes: ["E", "G", "Bb", "Db"], audio: ["E", "G2", "Bb2", "Db2"], chordAudio: "Edim"},
    { name: "A-diminished7", label: "A°7", notes: ["A", "C", "Eb", "Gb"], audio: ["A", "C", "Eb", "Gb2"], chordAudio: "Adim"},
    { name: "D-diminished7", label: "D°7", notes: ["D", "F", "Ab", "Cb"], audio: ["D", "F2", "Ab2", "B2"], chordAudio: "Ddim"},
    { name: "G-diminished7", label: "G°7", notes: ["G", "Bb", "Db", "Fb"], audio: ["G", "Bb", "Db", "E"], chordAudio: "Gdim"},
  ],
};
