export const chords = {
  major: [
    { name: "C-major", label: "C", notes: ["C", "E", "G"], audio: ["C", "E", "G2"], chordAudio: "C"},
    { name: "F-major", label: "F", notes: ["F", "A", "C"], audio: ["F", "A", "C"], chordAudio: "F"},
    { name: "Bb-major", label: "Bb", notes: ["Bb", "D", "F"], audio: ["Bb", "D", "F2"], chordAudio: "Bb"},
    { name: "Eb-major", label: "Eb", notes: ["Eb", "G", "Bb"], audio: ["Eb", "G2", "Bb2"], chordAudio: "Eb"},
    { name: "Ab-major", label: "Ab", notes: ["Ab", "C", "Eb"], audio: ["Ab2", "C2", "Eb2"], chordAudio: "Ab"},
    { name: "Db-major", label: "Db", notes: ["Db", "F", "Ab"], audio: ["Db", "F2", "Ab2"], chordAudio: "Db"},
    { name: "Gb-major", label: "Gb", notes: ["Gb", "Bb", "Db"], audio: ["Gb2", "Bb2", "Db2"], chordAudio: "Gb"},
    { name: "C#-major", label: "C#", notes: ["C#", "E#", "G#"], audio: ["Db", "F2", "Ab2"], chordAudio: "Db"},
    { name: "F#-major", label: "F#", notes: ["F#", "A#", "C#"], audio: ["Gb2", "Bb2", "Db2"], chordAudio: "Gb"},
    { name: "B-major", label: "B", notes: ["B", "D#", "F#"], audio: ["B", "Eb", "Gb2"], chordAudio: "B"},
    { name: "E-major", label: "E", notes: ["E", "G#", "B"], audio: ["E", "Ab2", "B2"], chordAudio: "E"},
    { name: "A-major", label: "A", notes: ["A", "C#", "E"], audio: ["A2", "Db2", "E2"], chordAudio: "A"},
    { name: "D-major", label: "D", notes: ["D", "F#", "A"], audio: ["D", "Gb2", "A2"], chordAudio: "D"},
    { name: "G-major", label: "G", notes: ["G", "B", "D"], audio: ["G2", "B2", "D2"], chordAudio: "G"},
  ],
  minor: [
    { name: "C-minor", label: "Cm", notes: ["C", "Eb", "G"] },
    { name: "F-minor", label: "Fm", notes: ["F", "Ab", "C"] },
    { name: "Bb-minor", label: "Bbm", notes: ["Bb", "Db", "F"] },
    { name: "Eb-minor", label: "Ebm", notes: ["Eb", "Gb", "Bb"] },
    { name: "Ab-minor", label: "Abm", notes: ["Ab", "Cb", "Eb"] },
    { name: "Db-minor", label: "Dbm", notes: ["Db", "Fb", "Ab"] },
    { name: "Gb-minor", label: "Gbm", notes: ["Gb", "Bbb", "Db"] },
    { name: "C#-minor", label: "C#m", notes: ["C#", "E", "G#"] },
    { name: "F#-minor", label: "F#m", notes: ["F#", "A", "C#"] },
    { name: "B-minor", label: "Bm", notes: ["B", "D", "F#"] },
    { name: "E-minor", label: "Em", notes: ["E", "G", "B"] },
    { name: "A-minor", label: "Am", notes: ["A", "C", "E"] },
    { name: "D-minor", label: "Dm", notes: ["D", "F", "A"] },
    { name: "G-minor", label: "Gm", notes: ["G", "Bb", "D"] },
  ],
  augmented: [
    { name: "C-augmented", label: "C+", notes: ["C", "E", "G#"] },
    { name: "F-augmented", label: "F+", notes: ["F", "A", "C#"] },
    { name: "Bb-augmented", label: "Bb+", notes: ["Bb", "D", "F#"] },
    { name: "Eb-augmented", label: "Eb+", notes: ["Eb", "G", "B"] },
    { name: "Ab-augmented", label: "Ab+", notes: ["Ab", "C", "E"] },
    { name: "Db-augmented", label: "Db+", notes: ["Db", "F", "A"] },
    { name: "Gb-augmented", label: "Gb+", notes: ["Gb", "Bb", "D"] },
    { name: "C#-augmented", label: "C#+", notes: ["C#", "E#", "G##"] },
    { name: "F#-augmented", label: "F#+", notes: ["F#", "A#", "C##"] },
    { name: "B-augmented", label: "B+", notes: ["B", "D#", "F##"] },
    { name: "E-augmented", label: "E+", notes: ["E", "G#", "B#"] },
    { name: "A-augmented", label: "A+", notes: ["A", "C#", "E#"] },
    { name: "D-augmented", label: "D+", notes: ["D", "F#", "A#"] },
    { name: "G-augmented", label: "G+", notes: ["G", "B", "D#"] },
  ],
  diminished: [
    { name: "C-diminished", label: "C°", notes: ["C", "Eb", "Gb"] },
    { name: "F-diminished", label: "F°", notes: ["F", "Ab", "Cb"] },
    { name: "Bb-diminished", label: "Bb°", notes: ["Bb", "Db", "Fb"] },
    { name: "Eb-diminished", label: "Eb°", notes: ["Eb", "Gb", "Bbb"] },
    { name: "Ab-diminished", label: "Ab°", notes: ["Ab", "Cb", "Ebb"] },
    { name: "Db-diminished", label: "Db°", notes: ["Db", "Fb", "Abb"] },
    { name: "Gb-diminished", label: "Gb°", notes: ["Gb", "Bbb", "Dbb"] },
    { name: "C#-diminished", label: "C#°", notes: ["C#", "E", "G"] },
    { name: "F#-diminished", label: "F#°", notes: ["F#", "A", "C"] },
    { name: "B-diminished", label: "B°", notes: ["B", "D", "F"] },
    { name: "E-diminished", label: "E°", notes: ["E", "G", "Bb"] },
    { name: "A-diminished", label: "A°", notes: ["A", "C", "Eb"] },
    { name: "D-diminished", label: "D°", notes: ["D", "F", "Ab"] },
    { name: "G-diminished", label: "G°", notes: ["G", "Bb", "Db"] },
  ],
  major7: [
    { name: "C-major7", label: "CM7", notes: ["C", "E", "G", "B"] },
    { name: "F-major7", label: "FM7", notes: ["F", "A", "C", "E"] },
    { name: "Bb-major7", label: "BbM7", notes: ["Bb", "D", "F", "A"] },
    { name: "Eb-major7", label: "EbM7", notes: ["Eb", "G", "Bb", "D"] },
    { name: "Ab-major7", label: "AbM7", notes: ["Ab", "C", "Eb", "G"] },
    { name: "Db-major7", label: "DbM7", notes: ["Db", "F", "Ab", "C"] },
    { name: "Gb-major7", label: "GbM7", notes: ["Gb", "Bb", "Db", "F"] },
    { name: "C#-major7", label: "C#M7", notes: ["C#", "E#", "G#", "B#"] },
    { name: "F#-major7", label: "F#M7", notes: ["F#", "A#", "C#", "E#"] },
    { name: "B-major7", label: "BM7", notes: ["B", "D#", "F#", "A#"] },
    { name: "E-major7", label: "EM7", notes: ["E", "G#", "B", "D#"] },
    { name: "A-major7", label: "AM7", notes: ["A", "C#", "E", "G#"] },
    { name: "D-major7", label: "DM7", notes: ["D", "F#", "A", "C#"] },
    { name: "G-major7", label: "GM7", notes: ["G", "B", "D", "F#"] },
  ],
};

// export const chordAudio = {
//     "C-chord": require("../../audio/C-chord.mp3"),
//     "F-chord": require("../../audio/F-chord.mp3"),
//     "Bb-chord": require("../../audio/Bb-chord.mp3"),
//     "Eb-chord": require("../../audio/Eb-chord.mp3"),
//     "Ab-chord": require("../../audio/Ab-chord.mp3"),
//     "Db-chord": require("../../audio/Db-chord.mp3"),
//     "C#-chord": require("../../audio/Db-chord.mp3"),
//     "Gb-chord": require("../../audio/Gb-chord.mp3"),
//     "F#-chord": require("../../audio/Gb-chord.mp3"),
//     "B-chord": require("../../audio/B-chord.mp3"),
//     "E-chord": require("../../audio/E-chord.mp3"),
//     "A-chord": require("../../audio/A-chord.mp3"),
//     "D-chord": require("../../audio/D-chord.mp3"),
//     "G-chord": require("../../audio/G-chord.mp3"),
// }

// export const noteAudio = {
//     "F": require("../../audio/F.mp3"),
//     "F#": require("../../audio/Gb.mp3"),
//     "Gb": require("../../audio/Gb.mp3"),
//     "G": require("../../audio/G.mp3"),
//     "G#": require("../../audio/Ab.mp3"),
//     "Ab": require("../../audio/Ab.mp3"),
//     "A": require("../../audio/A.mp3"),
//     "A#": require("../../audio/Bb.mp3"),
//     "Bb": require("../../audio/Bb.mp3"),
//     "B": require("../../audio/B.mp3"),
//     "C": require("../../audio/C.mp3"),
//     "C#": require("../../audio/Db.mp3"),
//     "Db": require("../../audio/Db.mp3"),
//     "D": require("../../audio/D.mp3"),
//     "D#": require("../../audio/Eb.mp3"),
//     "Eb": require("../../audio/Eb.mp3"),
//     "E": require("../../audio/E.mp3"),
//     "E#": require("../../audio/F.mp3"),
//     "C2": require("../../audio/C2.mp3"),
//     "C#2": require("../../audio/Db2.mp3"),
//     "Db2": require("../../audio/Db2.mp3"),
//     "D2": require("../../audio/D2.mp3"),
//     "D#2": require("../../audio/Eb2.mp3"),
//     "Eb2": require("../../audio/Eb2.mp3"),
//     "E2": require("../../audio/E2.mp3"),
//     "E#2": require("../../audio/F2.mp3"),
//     "F2": require("../../audio/F2.mp3"),
//     "F#2": require("../../audio/Gb2.mp3"),
//     "Gb2": require("../../audio/Gb2.mp3"),
//     "G2": require("../../audio/G2.mp3"),
//     "G#2": require("../../audio/Ab2.mp3"),
//     "Ab2": require("../../audio/Ab2.mp3"),
//     "A2": require("../../audio/A2.mp3"),
//     "A#2": require("../../audio/Bb2.mp3"),
//     "Bb2": require("../../audio/Bb2.mp3"),
//     "B2": require("../../audio/B2.mp3"),
// }

  // Record these missing ones Db2, D2, Eb2, E2,
